// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Models;

#nullable disable

namespace dotnetapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnetapp.Models.Batch", b =>
                {
                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchID"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BatchID");

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            BatchID = 1,
                            Capacity = 30,
                            EndTime = new DateTime(2024, 7, 17, 11, 5, 56, 419, DateTimeKind.Local).AddTicks(8536),
                            StartTime = new DateTime(2024, 7, 17, 10, 5, 56, 419, DateTimeKind.Local).AddTicks(8522)
                        },
                        new
                        {
                            BatchID = 2,
                            Capacity = 25,
                            EndTime = new DateTime(2024, 7, 18, 11, 5, 56, 419, DateTimeKind.Local).AddTicks(8543),
                            StartTime = new DateTime(2024, 7, 18, 10, 5, 56, 419, DateTimeKind.Local).AddTicks(8542)
                        },
                        new
                        {
                            BatchID = 3,
                            Capacity = 20,
                            EndTime = new DateTime(2024, 7, 19, 11, 5, 56, 419, DateTimeKind.Local).AddTicks(8545),
                            StartTime = new DateTime(2024, 7, 19, 10, 5, 56, 419, DateTimeKind.Local).AddTicks(8544)
                        },
                        new
                        {
                            BatchID = 4,
                            Capacity = 15,
                            EndTime = new DateTime(2024, 7, 20, 11, 5, 56, 419, DateTimeKind.Local).AddTicks(8547),
                            StartTime = new DateTime(2024, 7, 20, 10, 5, 56, 419, DateTimeKind.Local).AddTicks(8546)
                        },
                        new
                        {
                            BatchID = 5,
                            Capacity = 10,
                            EndTime = new DateTime(2024, 7, 21, 11, 5, 56, 419, DateTimeKind.Local).AddTicks(8548),
                            StartTime = new DateTime(2024, 7, 21, 10, 5, 56, 419, DateTimeKind.Local).AddTicks(8548)
                        });
                });

            modelBuilder.Entity("dotnetapp.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<int>("BatchID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.HasIndex("BatchID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("dotnetapp.Models.Student", b =>
                {
                    b.HasOne("dotnetapp.Models.Batch", "Batch")
                        .WithMany("Students")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("dotnetapp.Models.Batch", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
